/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: cia402_profile_torque.xdd
        File Version: 1

        Created:      2026-09-14 오전 9:00:00
        Created By:   
        Modified:     2026-09-14 오후 9:29:27
        Modified By:  

    Device Info:
        Vendor Name:  
        Vendor ID:    0
        Product Name: G474RE DNC motor drive
        Product ID:   1

        Description:  STM32G474 Profile Torque drive
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_RPDO 1
#define OD_CNT_TPDO 1


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 4


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint8_t x1003_pre_definedErrorField_sub0;
    uint32_t x1003_pre_definedErrorField[OD_CNT_ARR_1003];
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identityObject;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServer;
        uint32_t COB_IDServerToClient;
    } x1200_SDOServerParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t controlwordMapping;
        uint32_t modesOfOperationMapping;
        uint32_t targetVelocityMapping;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedObjects;
        uint32_t statuswordMapping;
        uint32_t modesDisplayMapping;
        uint32_t velocityActualValueMapping;
    } x1A00_TPDOMappingParameter;
    uint8_t x2000_motorPolePairs;
    float32_t x2001_permanentMagnetFluxLinkage;
    float32_t x2002_ratedPhaseCurrentPeak;
    float32_t x2003_maximumMechanicalSpeed;
    float32_t x2004_torqueCoefficient;
    uint16_t x603F_errorCode;
    uint16_t x6040_controlword;
    uint16_t x6041_statusword;
    int8_t x6060_modesOfOperation;
    int8_t x6061_modesOfOperationDisplay;
    int32_t x606C_velocityActualValue;
    int16_t x6071_targetTorque;
    uint16_t x6072_maximumTorque;
    uint32_t x6075_motorRatedCurrent;
    uint32_t x6076_motorRatedTorque;
    int16_t x6077_torqueActualValue;
    uint32_t x6080_maximumMotorSpeed;
    uint32_t x6087_torqueSlope;
    int32_t x60FF_targetVelocity;
} OD_RAM_t;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1014 &OD->list[3]
#define OD_ENTRY_H1017 &OD->list[4]
#define OD_ENTRY_H1018 &OD->list[5]
#define OD_ENTRY_H1200 &OD->list[6]
#define OD_ENTRY_H1400 &OD->list[7]
#define OD_ENTRY_H1600 &OD->list[8]
#define OD_ENTRY_H1800 &OD->list[9]
#define OD_ENTRY_H1A00 &OD->list[10]
#define OD_ENTRY_H2000 &OD->list[11]
#define OD_ENTRY_H2001 &OD->list[12]
#define OD_ENTRY_H2002 &OD->list[13]
#define OD_ENTRY_H2003 &OD->list[14]
#define OD_ENTRY_H2004 &OD->list[15]
#define OD_ENTRY_H603F &OD->list[16]
#define OD_ENTRY_H6040 &OD->list[17]
#define OD_ENTRY_H6041 &OD->list[18]
#define OD_ENTRY_H6060 &OD->list[19]
#define OD_ENTRY_H6061 &OD->list[20]
#define OD_ENTRY_H606C &OD->list[21]
#define OD_ENTRY_H6071 &OD->list[22]
#define OD_ENTRY_H6072 &OD->list[23]
#define OD_ENTRY_H6075 &OD->list[24]
#define OD_ENTRY_H6076 &OD->list[25]
#define OD_ENTRY_H6077 &OD->list[26]
#define OD_ENTRY_H6080 &OD->list[27]
#define OD_ENTRY_H6087 &OD->list[28]
#define OD_ENTRY_H60FF &OD->list[29]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[2]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[3]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[4]
#define OD_ENTRY_H1018_identityObject &OD->list[5]
#define OD_ENTRY_H1200_SDOServerParameter &OD->list[6]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[7]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[8]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[9]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[10]
#define OD_ENTRY_H2000_motorPolePairs &OD->list[11]
#define OD_ENTRY_H2001_permanentMagnetFluxLinkage &OD->list[12]
#define OD_ENTRY_H2002_ratedPhaseCurrentPeak &OD->list[13]
#define OD_ENTRY_H2003_maximumMechanicalSpeed &OD->list[14]
#define OD_ENTRY_H2004_torqueCoefficient &OD->list[15]
#define OD_ENTRY_H603F_errorCode &OD->list[16]
#define OD_ENTRY_H6040_controlword &OD->list[17]
#define OD_ENTRY_H6041_statusword &OD->list[18]
#define OD_ENTRY_H6060_modesOfOperation &OD->list[19]
#define OD_ENTRY_H6061_modesOfOperationDisplay &OD->list[20]
#define OD_ENTRY_H606C_velocityActualValue &OD->list[21]
#define OD_ENTRY_H6071_targetTorque &OD->list[22]
#define OD_ENTRY_H6072_maximumTorque &OD->list[23]
#define OD_ENTRY_H6075_motorRatedCurrent &OD->list[24]
#define OD_ENTRY_H6076_motorRatedTorque &OD->list[25]
#define OD_ENTRY_H6077_torqueActualValue &OD->list[26]
#define OD_ENTRY_H6080_maximumMotorSpeed &OD->list[27]
#define OD_ENTRY_H6087_torqueSlope &OD->list[28]
#define OD_ENTRY_H60FF_targetVelocity &OD->list[29]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = 0;\
    (config).CNT_ARR_1016 = 0;\
    (config).ENTRY_H1016 = NULL;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = NULL;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = 0;\
    (config).ENTRY_H1005 = NULL;\
    (config).ENTRY_H1006 = NULL;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
